version: '3.8'

services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - "8080:8080"
    environment:
      - CAMUNDA_DB_DRIVER=com.h2.Driver
      - CAMUNDA_DB_URL=jdbc:h2:mem:testdb
      - CAMUNDA_DB_USERNAME=sa
      - CAMUNDA_DB_PASSWORD=

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - camunda